name: polymer_dart_blog
description: A simple blog prototype, with MongoDB as Backend
dependencies:
  browser: any
  polymer: any
  start: any
  http: any
  bootjack: any
  intl: any
  mongo_dart: any
  route: any