name: polymer_dart_blog
description: A simple blog prototype, with OrientDB as Backend
dependencies:
  browser: any
  polymer: any
  start:
    git: https://github.com/lvivski/start.git
  http: any
  bootjack: any
  intl: any
  mongo_dart: any
  route: any